apiVersion: v1
kind: Service
metadata:
  name: agent-operator-trigger
  namespace: system
  labels:
    app.kubernetes.io/name: agent-operator
    app.kubernetes.io/component: trigger
spec:
  selector:
    app.kubernetes.io/name: agent-operator
    app.kubernetes.io/component: manager
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: trigger
