$schema: https://moonrepo.dev/schemas/project.json
language: unknown
layer: configuration
tags:
  - ci
tasks:
  github-actions-lint:
    command:
      - zizmor
      - --offline
      - .
    toolchain: [system, nix]
    inputs:
      - "**/*"
      - /flake.lock
      - /flake.nix
      - /nix/ci.nix
    options:
      cache: true
  ci-check:
    command: noop
    deps: [github-actions-lint]
    options:
      cache: false
