name: Setup Go CLI
description: Setup Go with caching for agent-cli-go

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25"
        cache-dependency-path: packages/cli/agent-cli-go/go.sum
