# Xonovex Platform - GitLab CI/CD Pipeline
# Mirrors the GitHub Actions workflows

image: node:24

variables:
  GIT_DEPTH: 0

stages:
  - ci
  - release

.workspace_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .moon/cache/

include:
  - local: .gitlab/workflows/ci.yml
  - local: .gitlab/workflows/release.yml
