$schema: https://moonrepo.dev/schemas/workspace.json
projects:
  - docs
  - packages/config/*
  - packages/cli/*
  - packages/lib/*
  - packages/plugins/*
  - packages/docker/*
vcs:
  hooks:
    commit-msg:
      - npx commitlint --edit $ARG1
  provider: github
  defaultBranch: main
  client: git
  sync: true
constraints:
  enforceLayerRelationships: true
hasher:
  optimization: performance
  walkStrategy: vcs
pipeline:
  autoCleanCache: true
  cacheLifetime: 7 days
  inheritColorsForPipedTasks: true
  logRunningCommand: true
