$schema: https://moonrepo.dev/schemas/workspace.json
projects:
  - packages/asset/*
  - packages/doc/*
  - packages/config/*
  - packages/agent/*
  - packages/agent/agent-cli-go-platforms/*
  - packages/shared/*
  - packages/plugin/*
  - packages/docker/*
  - packages/script/*
vcs:
  hooks:
    commit-msg:
      - npx commitlint --edit $ARG1
    pre-commit:
      - unset $(git rev-parse --local-env-vars 2>/dev/null || echo '') && .hooks/run-quality-checks.sh --staged --targets :lint,:typecheck --concurrency 4
  provider: github
  defaultBranch: main
  client: git
  sync: true
constraints:
  enforceLayerRelationships: true
hasher:
  optimization: performance
  walkStrategy: vcs
pipeline:
  autoCleanCache: true
  cacheLifetime: 7 days
  inheritColorsForPipedTasks: true
  logRunningCommand: true
