$schema: https://moonrepo.dev/schemas/tasks.json
extends: ./tag-typescript.yml
tasks:
  ts-build:
    deps: []
    options:
      mergeDeps: replace
  ts-test:
    deps: []
    options:
      mergeDeps: replace
  ts-test-watch:
    deps: []
    options:
      mergeDeps: replace
  ts-lint:
    deps:
      - ts-build
    options:
      mergeDeps: replace
  ts-lint-fix:
    deps:
      - ts-build
    options:
      mergeDeps: replace
  ts-typecheck:
    deps:
      - ts-build
    options:
      mergeDeps: replace
  ts-coverage:
    deps: []
    options:
      mergeDeps: replace
inheritedBy:
  tag: typescript-script
