$schema: https://moonrepo.dev/schemas/tasks.json
fileGroups:
  sources:
    - "**/*.sh"
  configs:
    - "/.editorconfig"
tasks:
  sh-lint:
    script: |
      shopt -s globstar nullglob
      files=(**/*.sh)
      if [ "${#files[@]}" -eq 0 ]; then
        echo 'No .sh files found'
      else
        shellcheck -x "${files[@]}"
      fi
    toolchain: [system, nix]
    inputs:
      - "@globs(sources)"
      - "/.editorconfig"
    options:
      cache: true
  sh-format:
    command:
      - shfmt
      - -w
      - .
    toolchain: [system, nix]
    inputs:
      - "@globs(sources)"
    options:
      cache: false
  sh-format-check:
    command:
      - shfmt
      - -d
      - .
    toolchain: [system, nix]
    inputs:
      - "@globs(sources)"
    options:
      cache: true
  lint:
    command: noop
    deps: [sh-lint]
    options:
      cache: false
      mergeDeps: append
  format-check:
    command: noop
    deps: [sh-format-check]
    options:
      cache: false
      mergeDeps: append
  ci-check:
    command: echo 'ci-check complete'
    deps: [lint, format-check]
    options:
      cache: false
inheritedBy:
  tag: shell
