$schema: https://moonrepo.dev/schemas/tasks.json
fileGroups:
  sources:
    - 'src/**/*'
  tests:
    - 'tests/**/*'
tasks:
  rust-lint:
    command:
      - cargo
      - clippy
      - --all-targets
      - --
      - -D
      - warnings
    toolchain: [system, nix]
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - Cargo.toml
      - Cargo.lock
    options:
      cache: true
  rust-format-check:
    command:
      - cargo
      - fmt
      - --check
    toolchain: [system, nix]
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
    options:
      cache: true
  lint:
    command: noop
    deps: [rust-lint]
    options:
      cache: false
      mergeDeps: append
  format-check:
    command: noop
    deps: [rust-format-check]
    options:
      cache: false
      mergeDeps: append
inheritedBy:
  tag: rust
