$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  command-format:
    command: [npm, run, fmt]
    inputs:
      - "**/*.md"
      - "*.config.*"
      - package.json
    outputs: []
    options:
      cache: false
      runInCI: false
  command-format-check:
    command: [npm, run, "fmt:check"]
    inputs:
      - "**/*.md"
      - "*.config.*"
      - package.json
    outputs: []
  format:
    command: noop
    deps: [command-format]
    options:
      cache: false
      runInCI: false
      mergeDeps: append
  format-check:
    command: noop
    deps: [command-format-check]
    options:
      cache: false
      mergeDeps: append
  ci-check:
    command: echo 'ci-check complete'
    deps: [build, format-check]
    options:
      cache: false
inheritedBy:
  tag: command
