$schema: https://moonrepo.dev/schemas/tasks.json
extends: ./tag-typescript.yml
fileGroups:
  configs:
    - '*.config.*'
    - tsconfig*.json
    - .eslintrc*
    - .prettierrc*
    - package.json
tasks:
  ts-test:
    script: echo 'no tests for config package'
    deps: []
    inputs: []
    outputs: []
    options:
      cache: false
      mergeDeps: replace
  ts-clean:
    script: rm -rf dist
    options:
      cache: false
inheritedBy:
  tag: typescript-config
