$schema: https://moonrepo.dev/schemas/tasks.json
implicitInputs:
- package.json
- tsconfig*.json
fileGroups:
  sources:
  - src/**/*
  configs:
  - '*.config.*'
  - tsconfig*.json
  - .eslintrc*
  - .prettierrc*
  - package.json
tasks:
  tsconfig-build:
    deps:
    - ^:build
    command:
    - npm
    - run
    - build
    inputs:
    - '@globs(sources)'
    - '@globs(configs)'
    outputs:
    - dist
    options:
      cache: true
      runDepsInParallel: true
  tsconfig-clean:
    script: rm -rf dist
    options:
      cache: false
  tsconfig-typecheck:
    command:
    - npm
    - run
    - typecheck
    deps:
    - tsconfig-build
    - ^:build
    inputs:
    - '@globs(sources)'
    - tsconfig*.json
    outputs: []
    options:
      cache: true
  tsconfig-lint:
    command:
    - npm
    - run
    - lint
    deps:
    - tsconfig-build
    - ^:build
    inputs:
    - '@globs(sources)'
    - '@globs(configs)'
    outputs: []
    options:
      cache: true
  tsconfig-lint-fix:
    command:
    - npm
    - run
    - lint:fix
    deps:
    - tsconfig-build
    - ^:build
    inputs:
    - '@globs(sources)'
    - '@globs(configs)'
    outputs: []
    options:
      cache: false
  tsconfig-format:
    command:
    - npm
    - run
    - fmt
    inputs:
    - '@globs(sources)'
    - '@globs(configs)'
    - '*.json'
    - '*.md'
    outputs: []
    options:
      cache: false
  tsconfig-format-check:
    command:
    - npm
    - run
    - fmt:check
    inputs:
    - '@globs(sources)'
    - '@globs(configs)'
    - '*.json'
    - '*.md'
    outputs: []
    options:
      cache: true
  build:
    command: noop
    deps: [tsconfig-build]
    options:
      cache: false
      mergeDeps: append
  lint:
    command: noop
    deps: [tsconfig-lint]
    options:
      cache: false
      mergeDeps: append
  typecheck:
    command: noop
    deps: [tsconfig-typecheck]
    options:
      cache: false
      mergeDeps: append
  format-check:
    command: noop
    deps: [tsconfig-format-check]
    options:
      cache: false
      mergeDeps: append
  ci-check:
    command: echo 'ci-check complete'
    deps: [build, lint, typecheck, format-check]
    options:
      cache: false
inheritedBy:
  tag: tsconfig
