/**
 * Generate bash completion script
 */
export function generateBashCompletion(): string {
  // Using array join to avoid template literal parsing issues
  const lines = [
    "# Bash completion for agent-cli",
    "# Source this file or add to ~/.bashrc",
    "",
    "_agent_cli_completions() {",
    "    local cur prev words cword",
    "    _init_completion || return",
    "",
    '    local commands="run completion"',
    '    local run_opts="-a --agent -p --provider -s --sandbox -H --home-dir -w --work-dir -c --config -N --no-network --network --bind --ro-bind -t --tmux --tmux-session --tmux-detach -v --verbose -d --debug -n --dry-run"',
    '    local completion_commands="bash list args"',
    '    local agents="claude opencode"',
    '    local providers="gemini gemini-claude glm gpt5-codex"',
    '    local sandboxes="none bwrap docker"',
    "",
    '    case "${words[1]}" in',
    "        run)",
    '            case "$prev" in',
    "                -a|--agent)",
    '                    COMPREPLY=( $(compgen -W "$agents" -- "$cur") )',
    "                    return",
    "                    ;;",
    "                -p|--provider)",
    '                    COMPREPLY=( $(compgen -W "$providers" -- "$cur") )',
    "                    return",
    "                    ;;",
    "                -s|--sandbox)",
    '                    COMPREPLY=( $(compgen -W "$sandboxes" -- "$cur") )',
    "                    return",
    "                    ;;",
    "                -H|--home-dir|-w|--work-dir|-c|--config|--bind|--ro-bind)",
    "                    _filedir -d",
    "                    return",
    "                    ;;",
    "            esac",
    '            COMPREPLY=( $(compgen -W "$run_opts" -- "$cur") )',
    "            ;;",
    "        completion)",
    "            if [[ $cword -eq 2 ]]; then",
    '                COMPREPLY=( $(compgen -W "$completion_commands" -- "$cur") )',
    '            elif [[ "${words[2]}" == "args" && $cword -eq 3 ]]; then',
    "                local slash_commands=$(agent-cli completion list --names-only 2>/dev/null)",
    '                COMPREPLY=( $(compgen -W "$slash_commands" -- "$cur") )',
    "            fi",
    "            ;;",
    "        *)",
    "            if [[ $cword -eq 1 ]]; then",
    '                COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
    "            fi",
    "            ;;",
    "    esac",
    "}",
    "",
    "complete -F _agent_cli_completions agent-cli",
  ];

  return lines.join("\n");
}
