name: Setup
description: Cache workspace and setup moon toolchain

inputs:
  cache-workspace:
    description: "Cache .moon/cache and node_modules"
    default: "true"

runs:
  using: composite
  steps:
    - if: inputs.cache-workspace != 'false'
      uses: actions/cache@v4
      with:
        path: |
          .moon/cache
          node_modules
        key: npm-moon-${{ runner.os }}-${{ hashFiles('package-lock.json', '.moon/**/*.yml') }}
        restore-keys: |
          npm-moon-${{ runner.os }}

    - uses: moonrepo/setup-toolchain@v0
    - uses: DeterminateSystems/nix-installer-action@main
    - if: inputs.cache-workspace != 'false'
      uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false
