name: Setup Nix
description: Install Nix with caching, optionally cache workspace dependencies

inputs:
  cache-workspace:
    description: Whether to cache .moon/cache, node_modules, and ~/go/pkg/mod
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: /nix
        key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
        restore-keys: |
          nix-${{ runner.os }}-

    - uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_conf: |
          build-users-group =

    - if: inputs.cache-workspace == 'true'
      uses: actions/cache@v4
      with:
        path: |
          .moon/cache
          node_modules
        key: npm-moon-${{ runner.os }}-${{ hashFiles('package-lock.json', '.moon/**/*.yml') }}
        restore-keys: |
          npm-moon-${{ runner.os }}-

    - if: inputs.cache-workspace == 'true'
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-${{ runner.os }}-
